# Generated by Django 4.2.13 on 2026-06-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Leave blank for no expiry', null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='max_responses',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited', null=True),
        ),
    ]
